CREATE TABLE tb_historico_moto
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    parte     VARCHAR(255),
    descricao VARCHAR(255),
    moto_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_tb_historico_moto PRIMARY KEY (id)
);

CREATE TABLE tb_moto
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    modelo        SMALLINT                                NOT NULL,
    placa         VARCHAR(255),
    data_cadastro date                                    NOT NULL,
    status        SMALLINT                                NOT NULL,
    tb_rfid       BIGINT,
    CONSTRAINT pk_tb_moto PRIMARY KEY (id)
);

CREATE TABLE tb_rfid
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome_area VARCHAR(255),
    latitude  VARCHAR(255),
    longitude VARCHAR(255),
    CONSTRAINT pk_tb_rfid PRIMARY KEY (id)
);

CREATE TABLE tb_usuario
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome  VARCHAR(255),
    email VARCHAR(255),
    senha VARCHAR(255),
    CONSTRAINT pk_tb_usuario PRIMARY KEY (id)
);

ALTER TABLE tb_moto
    ADD CONSTRAINT uc_tb_moto_tb_rfid UNIQUE (tb_rfid);

ALTER TABLE tb_historico_moto
    ADD CONSTRAINT FK_TB_HISTORICO_MOTO_ON_MOTO FOREIGN KEY (moto_id) REFERENCES tb_moto (id);

ALTER TABLE tb_moto
    ADD CONSTRAINT FK_TB_MOTO_ON_TB_RFID FOREIGN KEY (tb_rfid) REFERENCES tb_rfid (id);