CREATE TABLE tb_historico_moto
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    parte     VARCHAR(255),
    descricao VARCHAR(255),
    moto_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_tb_historico_moto PRIMARY KEY (id)
);

CREATE TABLE tb_moto
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    modelo        varchar(10)                                NOT NULL,
    placa         VARCHAR(255),
    data_cadastro DATE                                    NOT NULL,
    status        varchar(15)                                NOT NULL,
    tb_rfid       BIGINT,
    usuario_id    BIGINT                                   NOT NULL,
    CONSTRAINT pk_tb_moto PRIMARY KEY (id)
);

CREATE TABLE tb_rfid
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome_area VARCHAR(255),
    latitude  float(53),
    longitude float(53),
    CONSTRAINT pk_tb_rfid PRIMARY KEY (id)
);

CREATE TABLE tb_usuario
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome  VARCHAR(255),
    email VARCHAR(255),
    senha VARCHAR(255),
    role  VARCHAR(50) DEFAULT 'USER' NOT NULL,
    CONSTRAINT pk_tb_usuario PRIMARY KEY (id)
);

ALTER TABLE tb_moto
    ADD CONSTRAINT uc_tb_moto_tb_rfid UNIQUE (tb_rfid);

-- Chaves estrangeiras
ALTER TABLE tb_historico_moto
    ADD CONSTRAINT fk_tb_historico_moto_on_moto FOREIGN KEY (moto_id) REFERENCES tb_moto (id);

ALTER TABLE tb_moto
    ADD CONSTRAINT fk_tb_moto_on_tb_rfid FOREIGN KEY (tb_rfid) REFERENCES tb_rfid (id);

ALTER TABLE tb_moto
    ADD CONSTRAINT fk_tb_moto_on_usuario FOREIGN KEY (usuario_id) REFERENCES tb_usuario (id);



-- Usuário 1: Role = USER (padrão)
INSERT INTO tb_usuario (nome, email, senha, role)
VALUES ('João Silva', 'joao.silva@example.com', 'senha123', 'USER');

-- Usuário 2: Role = ADMIN
INSERT INTO tb_usuario (nome, email, senha, role)
VALUES ('Maria Santos', 'maria.santos@example.com', 'admin456', 'ADMIN');

-- RFID 1
INSERT INTO tb_rfid (nome_area, latitude, longitude)
VALUES ('Área A', -23.5505, -46.6333);

-- RFID 2
INSERT INTO tb_rfid (nome_area, latitude, longitude)
VALUES ('Área B', -22.9068, -43.1729);

-- Moto 1: Associada ao Usuário 1 (João Silva) e RFID 1 (Área A)
INSERT INTO tb_moto (modelo, placa, data_cadastro, status, tb_rfid, usuario_id)
VALUES ('SPORT', 'ABC1234', '2023-01-15', 'MANUTENCAO', 1, 1);

-- Moto 2: Associada ao Usuário 2 (Maria Santos) e RFID 2 (Área B)
INSERT INTO tb_moto (modelo, placa, data_cadastro, status, tb_rfid, usuario_id)
VALUES ('POP', 'DEF5678', '2023-02-20', 'REVISADA', 2, 2);

-- Histórico 1: Para Moto 1
INSERT INTO tb_historico_moto (parte, descricao, moto_id)
VALUES ('Motor', 'Manutenção realizada no motor.', 1);

-- Histórico 2: Para Moto 2
INSERT INTO tb_historico_moto (parte, descricao, moto_id)
VALUES ('Freio', 'Troca de pastilhas de freio.', 2);

UPDATE tb_usuario
SET senha = '$2a$10$L786A1K6KfRCZ3vLVo.o9eJU4lAFeOkmzXwRjose0OmvL7jZdiZN.'
WHERE email = 'maria.santos@example.com';

-- Adiciona a coluna usuario_id como opcional
ALTER TABLE tb_historico_moto ADD COLUMN usuario_id BIGINT;

-- Atualiza os registros existentes
UPDATE tb_historico_moto
SET usuario_id = 1
WHERE id = 1;

UPDATE tb_historico_moto
SET usuario_id = 2
WHERE id = 2;

-- Aplica a restrição NOT NULL
ALTER TABLE tb_historico_moto ALTER COLUMN usuario_id SET NOT NULL;

-- Adiciona a chave estrangeira
ALTER TABLE tb_historico_moto
    ADD CONSTRAINT fk_historico_usuario FOREIGN KEY (usuario_id) REFERENCES tb_usuario (id);