CREATE TABLE tb_rfid
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome_area VARCHAR(255),
    latitude  float(53),
    longitude float(53),
    CONSTRAINT pk_tb_rfid PRIMARY KEY (id)
);