CREATE TABLE tb_rfid
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome_area VARCHAR(255) NOT NULL,
    latitude  float(53) NOT NULL,
    longitude float(53) NOT NULL,
    CONSTRAINT pk_tb_rfid PRIMARY KEY (id)
);
