CREATE TABLE tb_moto
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    modelo        varchar(10)                                NOT NULL,
    placa         VARCHAR(255),
    data_cadastro DATE                                    NOT NULL,
    status        varchar(15)                                NOT NULL,
    tb_rfid       BIGINT,
    usuario_id    BIGINT                                   NOT NULL,
    CONSTRAINT pk_tb_moto PRIMARY KEY (id)
);

ALTER TABLE tb_moto
    ADD CONSTRAINT uc_tb_moto_tb_rfid UNIQUE (tb_rfid);

ALTER TABLE tb_moto
    ADD CONSTRAINT fk_tb_moto_on_tb_rfid FOREIGN KEY (tb_rfid) REFERENCES tb_rfid (id);

ALTER TABLE tb_moto
    ADD CONSTRAINT fk_tb_moto_on_usuario FOREIGN KEY (usuario_id) REFERENCES tb_usuario (id);